"""add_conversations_table

Revision ID: 2eda4d1ef2e9
Revises: e46d2a7c73f2
Create Date: 2025-10-03 05:25:55.009908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eda4d1ef2e9'
down_revision = 'e46d2a7c73f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('last_query', sa.Text(), nullable=True),
    sa.Column('last_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_last_interaction', 'conversations', ['user_id', 'last_interaction_at'], unique=False)
    op.create_index('idx_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_index('idx_user_updated', table_name='conversations')
    op.drop_index('idx_user_last_interaction', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
