"""Initial schema

Revision ID: 56a32ad5cc72
Revises: 
Create Date: 2025-10-02 02:08:02.054597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56a32ad5cc72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('is_private', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.BigInteger(), nullable=True),
    sa.Column('messages_per_day', sa.Float(), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('embedding_vector_id', sa.String(length=100), nullable=True),
    sa.Column('slack_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_table('entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_text', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('canonical_form', sa.String(length=500), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('related_channels', sa.JSON(), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_occurrence', 'entities', ['occurrence_count'], unique=False)
    op.create_index('idx_type_canonical', 'entities', ['entity_type', 'canonical_form'], unique=False)
    op.create_index(op.f('ix_entities_canonical_form'), 'entities', ['canonical_form'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_id_1', sa.BigInteger(), nullable=False),
    sa.Column('entity_id_2', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities', 'entity_relationships', ['entity_id_1', 'entity_id_2'], unique=False)
    op.create_index(op.f('ix_entity_relationships_entity_id_1'), 'entity_relationships', ['entity_id_1'], unique=False)
    op.create_index(op.f('ix_entity_relationships_entity_id_2'), 'entity_relationships', ['entity_id_2'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.Column('filetype', sa.String(length=50), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('slack_url', sa.String(length=1000), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('s3_text_key', sa.String(length=500), nullable=True),
    sa.Column('is_downloaded', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Integer(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('slack_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_created', 'files', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_filetype', 'files', ['filetype'], unique=False)
    op.create_index(op.f('ix_files_channel_id'), 'files', ['channel_id'], unique=False)
    op.create_index(op.f('ix_files_file_id'), 'files', ['file_id'], unique=True)
    op.create_index(op.f('ix_files_message_id'), 'files', ['message_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('thread_ts', sa.String(length=50), nullable=True),
    sa.Column('is_thread_parent', sa.Boolean(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('reply_users_count', sa.Integer(), nullable=True),
    sa.Column('text', mysql.LONGTEXT(), nullable=True),
    sa.Column('text_processed', mysql.LONGTEXT(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('has_code', sa.Boolean(), nullable=True),
    sa.Column('code_languages', sa.JSON(), nullable=True),
    sa.Column('has_files', sa.Boolean(), nullable=True),
    sa.Column('file_ids', sa.JSON(), nullable=True),
    sa.Column('has_links', sa.Boolean(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.JSON(), nullable=True),
    sa.Column('mentioned_users', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('edit_history', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index('idx_channel_timestamp', 'messages', ['channel_id', 'timestamp'], unique=False)
    op.create_index('idx_importance', 'messages', ['importance_score'], unique=False)
    op.create_index('idx_thread_timestamp', 'messages', ['thread_ts', 'timestamp'], unique=False)
    op.create_index('idx_user_timestamp', 'messages', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_thread_ts'), 'messages', ['thread_ts'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding', sa.JSON(), nullable=True),
    sa.Column('intent_type', sa.String(length=100), nullable=True),
    sa.Column('entities_extracted', sa.JSON(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('channel_filters', sa.JSON(), nullable=True),
    sa.Column('candidates_count', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('result_message_ids', sa.JSON(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('reranking_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Integer(), nullable=True),
    sa.Column('cache_key', sa.String(length=255), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_clicked_results', sa.JSON(), nullable=True),
    sa.Column('user_copied_content', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intent_created', 'query_logs', ['intent_type', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'query_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_created_at'), 'query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_query_id'), 'query_logs', ['query_id'], unique=True)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_ts', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('parent_message_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_user_id', sa.String(length=50), nullable=False),
    sa.Column('parent_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('participant_ids', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topic_classification', sa.String(length=100), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('key_decisions', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('total_reactions', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_reply_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('summary_vector_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_started', 'threads', ['channel_id', 'started_at'], unique=False)
    op.create_index('idx_importance', 'threads', ['importance_score'], unique=False)
    op.create_index(op.f('ix_threads_channel_id'), 'threads', ['channel_id'], unique=False)
    op.create_index(op.f('ix_threads_started_at'), 'threads', ['started_at'], unique=False)
    op.create_index(op.f('ix_threads_thread_ts'), 'threads', ['thread_ts'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('real_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('total_messages', sa.BigInteger(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('active_channels_count', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('frequently_mentioned_terms', sa.JSON(), nullable=True),
    sa.Column('preferred_topics', sa.JSON(), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('slack_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threads_thread_ts'), table_name='threads')
    op.drop_index(op.f('ix_threads_started_at'), table_name='threads')
    op.drop_index(op.f('ix_threads_channel_id'), table_name='threads')
    op.drop_index('idx_importance', table_name='threads')
    op.drop_index('idx_channel_started', table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_query_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_created_at'), table_name='query_logs')
    op.drop_index('idx_user_created', table_name='query_logs')
    op.drop_index('idx_intent_created', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_ts'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index('idx_user_timestamp', table_name='messages')
    op.drop_index('idx_thread_timestamp', table_name='messages')
    op.drop_index('idx_importance', table_name='messages')
    op.drop_index('idx_channel_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_files_message_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_id'), table_name='files')
    op.drop_index(op.f('ix_files_channel_id'), table_name='files')
    op.drop_index('idx_filetype', table_name='files')
    op.drop_index('idx_channel_created', table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_entity_relationships_entity_id_2'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_entity_id_1'), table_name='entity_relationships')
    op.drop_index('idx_entities', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_form'), table_name='entities')
    op.drop_index('idx_type_canonical', table_name='entities')
    op.drop_index('idx_occurrence', table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
