"""add_knowledge_graph_tables

Revision ID: 98c030b0b8a6
Revises: 20251006_2330
Create Date: 2025-10-08 17:38:24.862325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98c030b0b8a6'
down_revision = '20251006_2330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('significant_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=500), nullable=False),
    sa.Column('event_description', sa.String(length=2000), nullable=True),
    sa.Column('entity_ids', sa.JSON(), nullable=True),
    sa.Column('primary_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('channels_discussed', sa.JSON(), nullable=True),
    sa.Column('message_ids', sa.JSON(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('before_metrics', sa.JSON(), nullable=True),
    sa.Column('after_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_time', 'significant_events', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_event_type_time', 'significant_events', ['event_type', 'start_time'], unique=False)
    op.create_index(op.f('ix_significant_events_event_id'), 'significant_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_significant_events_event_type'), 'significant_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_significant_events_primary_entity_id'), 'significant_events', ['primary_entity_id'], unique=False)
    op.create_index(op.f('ix_significant_events_start_time'), 'significant_events', ['start_time'], unique=False)
    op.create_table('user_expertise',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('reactions_received', sa.Integer(), nullable=True),
    sa.Column('replies_received', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('expertise_score', sa.Float(), nullable=True),
    sa.Column('first_interaction', sa.DateTime(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=False),
    sa.Column('recent_activity_score', sa.Float(), nullable=True),
    sa.Column('primary_channels', sa.JSON(), nullable=True),
    sa.Column('sample_messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expertise_score', 'user_expertise', ['expertise_score'], unique=False)
    op.create_index('idx_user_entity', 'user_expertise', ['user_id', 'entity_id'], unique=True)
    op.create_index('idx_user_scores', 'user_expertise', ['user_id', 'expertise_score'], unique=False)
    op.create_index(op.f('ix_user_expertise_entity_id'), 'user_expertise', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_expertise_expertise_score'), 'user_expertise', ['expertise_score'], unique=False)
    op.create_index(op.f('ix_user_expertise_user_id'), 'user_expertise', ['user_id'], unique=False)
    op.drop_index('idx_category_active', table_name='golden_tests')
    op.drop_index('idx_created_at', table_name='golden_tests')
    op.drop_index('idx_query_type_active', table_name='golden_tests')
    op.drop_index('idx_test_id', table_name='golden_tests')
    op.drop_index('test_id', table_name='golden_tests')
    op.drop_table('golden_tests')
    op.drop_index('idx_run_id', table_name='evaluation_results')
    op.drop_index('idx_run_passed', table_name='evaluation_results')
    op.drop_index('idx_run_test', table_name='evaluation_results')
    op.drop_index('idx_test_id', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index('idx_run_id', table_name='evaluation_runs')
    op.drop_index('idx_started_at', table_name='evaluation_runs')
    op.drop_index('run_id', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    # Skip dropping idx_api_keys_created_by - needed by foreign key
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_team_id', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_team_id'), 'api_keys', ['team_id'], unique=False)
    # Skip foreign key modification to avoid constraint issues
    op.alter_column('query_logs', 'query_was_rewritten',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('query_logs', 'query_was_expanded',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('team_id', table_name='workspaces')
    op.drop_index('ix_workspaces_team_id', table_name='workspaces')
    op.create_index(op.f('ix_workspaces_team_id'), 'workspaces', ['team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_team_id'), table_name='workspaces')
    op.create_index('ix_workspaces_team_id', 'workspaces', ['team_id'], unique=False)
    op.create_index('team_id', 'workspaces', ['team_id'], unique=True)
    op.alter_column('query_logs', 'query_was_expanded',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('query_logs', 'query_was_rewritten',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # Skip foreign key modification to avoid constraint issues
    op.drop_index(op.f('ix_api_keys_team_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('idx_api_keys_team_id', 'api_keys', ['team_id'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=True)
    # Skip idx_api_keys_created_by - already exists
    op.create_table('evaluation_runs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('run_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('model_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('retrieval_config', mysql.JSON(), nullable=True),
    sa.Column('total_tests', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('passed_tests', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('failed_tests', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('avg_precision_at_5', mysql.FLOAT(), nullable=True),
    sa.Column('avg_recall_at_5', mysql.FLOAT(), nullable=True),
    sa.Column('avg_mrr', mysql.FLOAT(), nullable=True),
    sa.Column('avg_ndcg', mysql.FLOAT(), nullable=True),
    sa.Column('started_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('run_id', 'evaluation_runs', ['run_id'], unique=True)
    op.create_index('idx_started_at', 'evaluation_runs', ['started_at'], unique=False)
    op.create_index('idx_run_id', 'evaluation_runs', ['run_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('test_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('retrieved_message_ids', mysql.JSON(), nullable=True),
    sa.Column('retrieval_scores', mysql.JSON(), nullable=True),
    sa.Column('precision_at_5', mysql.FLOAT(), nullable=True),
    sa.Column('recall_at_5', mysql.FLOAT(), nullable=True),
    sa.Column('reciprocal_rank', mysql.FLOAT(), nullable=True),
    sa.Column('ndcg_at_5', mysql.FLOAT(), nullable=True),
    sa.Column('generated_answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('answer_similarity_score', mysql.FLOAT(), nullable=True),
    sa.Column('passed', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('failure_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('latency_ms', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evaluated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_test_id', 'evaluation_results', ['test_id'], unique=False)
    op.create_index('idx_run_test', 'evaluation_results', ['run_id', 'test_id'], unique=False)
    op.create_index('idx_run_passed', 'evaluation_results', ['run_id', 'passed'], unique=False)
    op.create_index('idx_run_id', 'evaluation_results', ['run_id'], unique=False)
    op.create_table('golden_tests',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('test_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('test_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('query_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('expected_message_ids', mysql.JSON(), nullable=True),
    sa.Column('expected_answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('expected_entities', mysql.JSON(), nullable=True),
    sa.Column('expected_channels', mysql.JSON(), nullable=True),
    sa.Column('min_relevance_score', mysql.FLOAT(), server_default=sa.text("'0.7'"), nullable=True),
    sa.Column('required_in_top_k', mysql.INTEGER(), server_default=sa.text("'5'"), autoincrement=False, nullable=True),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('difficulty', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('test_id', 'golden_tests', ['test_id'], unique=True)
    op.create_index('idx_test_id', 'golden_tests', ['test_id'], unique=False)
    op.create_index('idx_query_type_active', 'golden_tests', ['query_type', 'is_active'], unique=False)
    op.create_index('idx_created_at', 'golden_tests', ['created_at'], unique=False)
    op.create_index('idx_category_active', 'golden_tests', ['category', 'is_active'], unique=False)
    op.drop_index(op.f('ix_user_expertise_user_id'), table_name='user_expertise')
    op.drop_index(op.f('ix_user_expertise_expertise_score'), table_name='user_expertise')
    op.drop_index(op.f('ix_user_expertise_entity_id'), table_name='user_expertise')
    op.drop_index('idx_user_scores', table_name='user_expertise')
    op.drop_index('idx_user_entity', table_name='user_expertise')
    op.drop_index('idx_expertise_score', table_name='user_expertise')
    op.drop_table('user_expertise')
    op.drop_index(op.f('ix_significant_events_start_time'), table_name='significant_events')
    op.drop_index(op.f('ix_significant_events_primary_entity_id'), table_name='significant_events')
    op.drop_index(op.f('ix_significant_events_event_type'), table_name='significant_events')
    op.drop_index(op.f('ix_significant_events_event_id'), table_name='significant_events')
    op.drop_index('idx_event_type_time', table_name='significant_events')
    op.drop_index('idx_event_time', table_name='significant_events')
    op.drop_table('significant_events')
    # ### end Alembic commands ###
