"""Auto migration

Revision ID: e46d2a7c73f2
Revises: 56a32ad5cc72
Create Date: 2025-10-02 09:59:52.886075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46d2a7c73f2'
down_revision = '56a32ad5cc72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
